return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "black",
        "commitlint",
        "cspell",
        "css-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "flake8",
        "isort",
        "jq",
        "markdownlint",
        "mypy",
        "prettier",
        "pyright",
        "ruff",
        "shellcheck",
        "shfmt",
        "terraform-ls",
        "vetur-vls",
        "vue-language-server",
        "yamllint",
      },
    },
  },
}
